csv_download.Rmd:
  path: dev/csv_download.Rmd
  state: active
  R:
  - R/connect_to_browser.R
  - R/disconnect_from_browser.R
  - R/download_csv_auto.R
  - R/download_csv_schedule.R
  tests: []
  vignettes: vignettes/basic-usage.Rmd
  inflate:
    flat_file: dev/csv_download.Rmd
    vignette_name: Basic Usage
    open_vignette: true
    check: true
    document: true
    overwrite: ask
