---
title: "flat_full.Rmd for working package"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{=html}
<!-- 
Run this 'development' chunk

Store every call to library() that you need to run chunks line by line, as in a classical Rmd for analysis
-->
```
```{r development, include=FALSE}
library(testthat)
library(purrr)
library(RSelenium)
```

```{=html}
<!--
# Description of your package

This will fill the description of your package.
Fill and run the content of this chunk, before anything else. 

Note: when you will use other flat templates, this part will be in a separate file. Do not be surprised!
-->
```
```{r description, eval=FALSE}
# Describe your package
fusen::fill_description(
  pkg = here::here(),
  fields = list(
    Title = "Breeding Tools",
    Description = "An R package that can automatically download Pig Performance Test Station of Nedap.",
    `Authors@R` = c(
      person("Guo Meng", email = "tony2015116@163.com", role = c("aut", "cre")),
      person(given = "Guo Meng", role = "cph")
    )
  ),
  overwrite=T
)
# Define License with use_*_license()
usethis::use_mit_license("Guo Meng")
#usethis::use_ccby_license()
```

# download_free_hands

This is the first function of our package. You can free up you hands and download pig performance test station data using function `download_free_hands()`.

```{=html}
<!-- 
This first section shows:

- the three parts necessary for a package: 'function', 'examples' and 'tests'.  
  + Note that the three following chunks have names accordingly.

-->
```
```{r function-download_free_hands}
#' download free hands
#' 
#' @description
#'
#' `download_free_hands()` is deprecated. We will soon be totally
#' 
#' @param location Numeric value in string format
#' @param data_date The dates of data download
#' @param url The url of pig performance test station website
#' @param username The username of pig performance test station website
#' @param password The password of pig performance test station website
#' @param ... other parameters
#'
#' @return CSV files in the download path of your Google Chrome web browser.
#' @export

download_free_hands <- function(location, data_date, url, username, password, ...){
  remDr <- RSelenium::remoteDriver(remoteServerAddr = "127.0.0.1"
                        , port = 4444
                        , browserName = "chrome")#连接Server

  remDr$open() #打开浏览器
  remDr$navigate(url) #打开网址

  login_user <- '//*[@id="frmLogin"]/div[2]/input'
  login_passwd <- '//*[@id="frmLogin"]/div[3]/input'

  login_user_ele<-remDr$findElement("xpath",login_user)
  login_passwd_ele<-remDr$findElement("xpath",login_passwd)
  user<-list(username)
  pass<-list(password)
  login_user_ele$sendKeysToElement(user)
  login_passwd_ele$sendKeysToElement(pass)

  login <- '//*[@id="login_button"]'
  login_ele<-remDr$findElement("xpath",login)
  remDr$mouseMoveToLocation(webElement = login_ele)
  remDr$click()

  #Sys.sleep(5)
  Sys.sleep(sample(10,1))

  iter_download <- function(station, data_date, ...){
    #选择nedap网站《报告》
    choose_item <- '/html/body/div[1]/div[1]/ul/li[4]/a'
    choose_ele<-remDr$findElement("xpath",choose_item)
    remDr$mouseMoveToLocation(webElement = choose_ele)
    remDr$click()

    #选择<报告>中的<下载csv数据>
    download_item <- '//*[@id="reports_page"]/div[2]/div/div[3]/ol/li[4]/a'
    #download_item <- '//*[@id="reports_page"]/div[2]/div/div[3]/ol/li[1]/a'
    download_ele<-remDr$findElement("xpath",download_item)
    remDr$mouseMoveToLocation(webElement = download_ele)
    remDr$click()

    #choose_locations
    location_start <- '//*[@id="criteria"]/report-selection-range/div/div/div/div[1]/input'
    location_end <- '//*[@id="criteria"]/report-selection-range/div/div/div/div[2]/input'
    location_ele_start<-remDr$findElement("xpath",location_start)
    location_ele_end<-remDr$findElement("xpath",location_end)

    location_ele_start$clearElement() #清空输入框内容
    location_ele_end$clearElement() #清空输入框内容

    location_start_num <- list(station, key = "enter")
    location_ele_start$sendKeysToElement(location_start_num)
    location_ele_end$clickElement()#单击鼠标
    #选择下载日期
    date_start <- '//*[@id="datetimepicker0"]/input'
    date_end <- '//*[@id="datetimepicker1"]/input'
    date_ele_start<-remDr$findElement("xpath",date_start)
    date_ele_end<-remDr$findElement("xpath",date_end)

    date_ele_start$clearElement() #清空输入框内容

    date_need_to_download <- stringr::str_replace_all(as.character(data_date),"-",".")

    date_start_num <- list(date_need_to_download, key = "enter")
    date_end_num <- list(date_need_to_download, key = "enter")
    date_ele_start$sendKeysToElement(date_start_num)
    date_ele_end$clearElement()
    date_ele_end$sendKeysToElement(date_end_num)

    #download csv数据
    download_button <- '//*[@id="reports_download_csv_data"]/div[4]/button'
    download_button_ele<-remDr$findElement("xpath",download_button)
    remDr$mouseMoveToLocation(webElement = download_button_ele)
    remDr$click()

    remDr$refresh() #刷新网页
  }
  purrr::walk2(location, data_date, iter_download, ...)
  remDr$quit()
}
```

```{=html}
<!--
Here is an example on how to use the function.
This should be a reproducible and working example
-->
```
```{r examples-download_free_hands}
user_name = "隆鑫场测定一区"
stations = "101"
download_date = "2023-02-11"
download_free_hands(location = stations, 
                    data_date = download_date, 
                    url = Sys.getenv("web_url"), 
                    username = user_name, 
                    password = Sys.getenv("user_password"))

```

```{=html}
<!--
Here are some unit tests to verify the function works as expected.
-->
```
```{r tests-download_free_hands}
user_name = "隆鑫场测定一区"
stations = "101"
download_date = "2023-02-11"
test_that("download_free_hand works", {
  expect_no_error(
    download_free_hands(location = stations, 
                                   data_date = download_date, 
                                   url = Sys.getenv("web_url"),
                                   username = user_name, 
                                   password = Sys.getenv("user_password")), 
                  message = "somethings go wrong")
})
```

That's it ! This the end of the documented story of our package. All components are there.

```{=html}
<!-- 
# Inflate your package

You're one inflate from paper to box.
Build your package from this very Rmd using `fusen::inflate()` 
-->
```
# download_free_brain

```{r function-download_free_brain}
#' download free brain
#' 
#' @description
#'
#' `download_free_brain()` is deprecated. We will soon be totally
#' 
#' @param location Numeric value in string format
#' @param data_date The dates of data download
#' @param ... other parameters
#' 
#' @return CSV files in the download path of your Google Chrome web browser.
#' @export

download_free_brain <- function(location, data_date, ...){ 
  purrr::map(data_date, ~download_free_hands(location, ...), ...)
}
```

```{r example-download_free_brain}
user_name = "隆鑫场测定一区"
stations = purrr::map_chr(seq(101L,103L,1L), c)
download_date = seq(as.Date("2023-02-01"),as.Date("2023-02-03"),1)
download_free_brain(location = stations, 
                    data_date = download_date, 
                    url = Sys.getenv("web_url"), 
                    username = user_name, 
                    password = Sys.getenv("user_password"))
```

```{r tests-download_free_brain}
user_name = "隆鑫场测定一区"
stations = purrr::map_chr(seq(101L,103L,1L), c)
download_date = seq(as.Date("2023-02-01"),as.Date("2023-02-03"),1)
test_that("download_free_brain works", {
  expect_no_error(
    download_free_brain(location = stations, 
                                   data_date = download_date, 
                                   url = Sys.getenv("web_url"),
                                   username = user_name, 
                                   password = Sys.getenv("user_password")), 
                  message = "somethings go wrong")
})
```

```{r development-inflate, eval=FALSE}
fusen::inflate(flat_file = "dev/flat_full.Rmd",
               check = F)

#fusen::load_flat_functions(flat_file = "dev/flat_full.Rmd")

```

```{=html}
<!-- 
- Verify your `"DESCRIPTION"` file has been updated
- Verify your function is in `"R/"` directory
- Verify your test is in `"tests/testthat/"` directory
- Verify this Rmd appears in `"vignettes/"` directory 
-->
```
