# WARNING - Generated by {fusen} from /dev/flat_teaching.Rmd: do not edit by hand

test_that("download_by_hand works", {
  expect_no_error(download_by_hand(location = "101L",
                                   data_date = "2023-02-11",
                                   url = "https://yxlxppt01.vpu-online.cn/login/LoginPage.web",
                                   username = "隆鑫场测定一区",
                                   password = "yangxianglongxin1234"), 
                  message = "somethings go wrong")
})
