# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

user_name = "隆鑫场测定一区"
stations = purrr::map_chr(seq(101L,103L,1L), c)
download_date = seq(as.Date("2023-02-01"),as.Date("2023-02-03"),1)
test_that("download_free_brain works", {
  expect_no_error(
    download_free_brain(location = stations, 
                                   data_date = download_date, 
                                   url = Sys.getenv("web_url"),
                                   username = user_name, 
                                   password = Sys.getenv("user_password")), 
                  message = "somethings go wrong")
})
