# WARNING - Generated by {fusen} from /dev/flat_teaching.Rmd: do not edit by hand

test_that("download_by_hand works", {
  expect_no_error(download_by_hand(location = Sys.getenv("stations"),
                                   data_date = Sys.getenv("download_date"),
                                   url = Sys.getenv("web_url"),
                                   username = Sys.getenv("user_name"),
                                   password = Sys.getenv("user_password")), 
                  message = "somethings go wrong")
})
