# WARNING - Generated by {fusen} from dev/csv_download.Rmd: do not edit by hand

#' Start selenium webdriver service
#' 
#' @description
#'
#' `connect_to_browser()` is used to start the selenium webdriver service.
#' 
#' @param dest_dir The path of chrome browser dirver and selenium server.
#'
#' @return NULL
#' 
#' @importFrom wdauto "get_cd" "get_ss" "auto_cs"
#' @export
#' @examples
#' connect_to_browser(dest_dir = "C:/Users/Dell/Desktop/test")
connect_to_browser <- function(dest_dir) {
  wdauto::get_cd(dest_dir)
  wdauto::get_ss(dest_dir)
  wdauto::auto_cs(dest_dir)
}
