# WARNING - Generated by {fusen} from /dev/csv_download.Rmd: do not edit by hand

#' setup chrome or edge broser dirver and selenium server
#' 
#' @description
#'
#' `connect_to_browser()` is deprecated. We will soon be totally
#' 
#' @param browser The browser you can choose chrome or edge, default is chrome
#' @param download_path The path of chrome or edge broser dirver and selenium server
#'
#' @return NULL
#' 
#' @importFrom utils "download.file" "tail" "unzip"
#' @export
#' @examples
#' connect_to_browser(browser = "chrome", download_path = "C:/Users/Dell/Downloads/selenium")
#' connect_to_browser(browser = "edge", download_path = "C:/Users/Dell/Downloads/selenium")
connect_to_browser <- function(browser = "chrome", download_path) {
  # 参数检查
  if (!is.character(browser) || !browser %in% c("chrome", "edge")) {
    stop("Error: Invalid browser specified. Supported browsers are 'Chrome' or 'Microsoft Edge'.")
  }

  if (!is.character(download_path) || download_path == "") {
    stop("Error: 'download_path' argument must be a valid non-empty string.")
  }

  # 确保下载路径存在
  dir.create(download_path, showWarnings = FALSE)

  # 生成函数check_browsers_installed检查浏览器安装情况
  check_browsers_installed <- function(browser_name = NULL) {
    browsers <- list(
      list(
        name = "Chrome",
        reg_key = "HKEY_CURRENT_USER\\Software\\Google\\Chrome\\BLBeacon",
        version_var = "version"
      ),
      list(
        name = "Microsoft Edge",
        reg_key = "HKEY_CURRENT_USER\\Software\\Microsoft\\Edge\\BLBeacon",
        version_var = "version"
      )
    )

    if (!is.null(browser_name)) {
      browsers <- Filter(function(browser) browser$name == browser_name, browsers)
    }

    for (browser in browsers) {
      reg_query <- system(paste("reg query", shQuote(browser$reg_key), "/v", browser$version_var), intern = TRUE)

      if (length(reg_query) > 0) {
        browser_version <- regmatches(reg_query, regexpr("\\d+\\.\\d+\\.\\d+", reg_query))
        cat(browser$name, "is installed on this computer. Version:", browser_version, "\n")
      } else {
        cat("Error:", browser$name, "version not found.\n")
      }
    }
  }

  # 生成函数get_latest_release_chrome获取chrome驱动最新版本
  get_latest_release_chrome <- function(base_url, backup_url) {

    reg_query <- system("reg query \"HKEY_CURRENT_USER\\Software\\Google\\Chrome\\BLBeacon\" /v version", intern = TRUE)

    browser_version <- regmatches(reg_query, regexpr("\\d+\\.\\d+\\.\\d+", reg_query))
    browser_major_version <- regmatches(reg_query, regexpr("\\d+", reg_query))

    # 尝试从主要网址获取最新版本
    response <- tryCatch(httr::GET(paste0(base_url, "/LATEST_RELEASE_", browser_version)), error = function(e) NULL)

    # 如果主要网址失败，尝试从备份网址获取最新版本
    if (is.null(response) || httr::http_status(response)$category != "Success") {
      response <- httr::GET(paste0(backup_url, "/LATEST_RELEASE_", browser_version))
    }

    # 如果找不到完全匹配的驱动程序，尝试下载与浏览器主要版本号相同的最新驱动程序
    if (is.null(response) || httr::http_status(response)$category != "Success") {
      response <- tryCatch(httr::GET(paste0(base_url, "/LATEST_RELEASE_", browser_major_version)), error = function(e) NULL)
    }#使用closeset_version替代browser_major_version

    # 如果仍然无法获取版本信息，报错并退出
    if (is.null(response) || httr::http_status(response)$category != "Success") {
      cat("Error: Failed to download ChromeDriver from the provided URL. Please check the URL and try again.")
      return()
    }
    latest_release <- httr::content(response, as = "text", encoding = "UTF-8")
    # 获取计算机操作系统信息
    os <- tolower(Sys.info()[1])
    # 根据操作系统类型选择 Edge 驱动程序下载 URL
    if (os == "windows") {
      system_type <- Sys.info()["machine"]
      if (system_type == "x86-64") {
        download_url <- paste0(base_url, "/", latest_release, "/chromedriver_win32.zip")
      }
    } else if (os == "linux") {
      download_url <- paste0(base_url, "/", latest_release, "/chromedriver_linux64.zip")
    } else if (os == "darwin") {
      system_type <- Sys.info()["machine"]
      if (system_type == "arm64") {
        download_url <- paste0(base_url, "/", latest_release, "/chromedriver_mac_arm64.zip")
      } else if (system_type == "x86-64") {
        if (Sys.getenv("APPLE_SILICON_DEVICE") == "true") {
          download_url <- paste0(base_url, "/", latest_release, "/chromedriver_mac64.zip")
        }
      } else {
        # 不支持32位Mac系统
        stop("Unsupported system type: macOS 32-bit")
      }
    } else {
      # 不支持其他操作系统
      stop("Unsupported system type:", os)
    }
    return(download_url)
  }

  # 生成函数get_latest_release_edge获取edge驱动最新版本
  get_latest_release_edge <- function(base_url) {

    reg_query_edge <- system("reg query \"HKEY_CURRENT_USER\\Software\\Microsoft\\Edge\\BLBeacon\" /v version", intern = TRUE)

    edge_version <- regmatches(reg_query_edge, regexpr("\\d+\\.\\d+\\.\\d+", reg_query_edge))

    #page <- rvest::read_html(base_url)
    response <- httr::GET("https://msedgedriver.azureedge.net")
    html_content <- httr::content(response, as = "text", encoding = "UTF-8")

    # 解析页面内容，提取版本链接
    download_url <- rvest::read_html(html_content) |> rvest::html_nodes("url") |> rvest::html_text()
    # # Extract the table containing the version information
    # download_url <- rvest::html_nodes(page, "url") %>% html_text()
    # 构建 Edge 驱动下载 URL
    version_numbers <- sapply(download_url, function(x) gsub(".*/([0-9]+\\.[0-9]+\\.[0-9]+)\\.[0-9]+/.*", "\\1", x))
    #print(version_numbers)

    # 将版本号和浏览器版本转换为数值
    numeric_versions <- as.numeric(gsub("\\.", "", version_numbers))
    numeric_browser_version <- as.numeric(gsub("\\.", "", edge_version))

    # 提取大版本号
    major_versions <- as.integer(gsub("(\\d+)\\.\\d+\\.\\d+", "\\1", version_numbers))
    major_browser_version <- as.integer(gsub("(\\d+)\\.\\d+\\.\\d+", "\\1", edge_version))

    # 寻找小于等于浏览器版本的驱动程序版本，但不小于一个大版本
    compatible_versions <- version_numbers[(numeric_versions <= numeric_browser_version) & (major_versions >= major_browser_version - 1)]

    # 如果存在兼容版本，选择最接近的版本；否则返回错误或警告
    if (length(compatible_versions) > 0) {
      closest_version <- max(compatible_versions)
    } else {
      print("No compatible driver version found.")
    }
    # 找到“closest_version”的索引
    index <- which(compatible_versions == closest_version)

    # 获取该字符串的名称
    name <- names(compatible_versions)[index]

    # 获取计算机操作系统信息
    os <- tolower(Sys.info()[1])

    # 根据操作系统类型选择 Edge 驱动程序下载 URL
    if (os == "windows") {
      system_type <- Sys.info()["machine"]
      if (system_type == "x86-64") {
        selected_urls <- name[grepl(paste("win64", collapse = "|"), name)]
        edge_driver_download_url <- sample(selected_urls, 1)
      } else {
        selected_urls <- name[grepl(paste("win32", collapse = "|"), name)]
        edge_driver_download_url <- sample(selected_urls, 1)
      }
    } else if (os == "linux") {
      selected_urls <- name[grepl(paste("linux64", collapse = "|"), name)]
      edge_driver_download_url <- sample(selected_urls, 1)
    } else if (os == "darwin") {
      system_type <- Sys.info()["machine"]
      if (system_type == "arm64") {
        selected_urls <- name[grepl(paste("arm64", collapse = "|"), name)]
        edge_driver_download_url <- sample(selected_urls, 1)
      } else if (system_type == "x86-64") {
        if (Sys.getenv("APPLE_SILICON_DEVICE") == "true") {
          selected_urls <- name[grepl(paste("mac64_m1", collapse = "|"), name)]
          edge_driver_download_url <- sample(selected_urls, 1)
        } else {
          selected_urls <- name[grepl(paste("mac64", collapse = "|"), name)]
          edge_driver_download_url <- sample(selected_urls, 1)
        }
      } else {
        # 不支持32位Mac系统
        stop("Unsupported system type: macOS 32-bit")
      }
    } else {
      # 不支持其他操作系统
      stop("Unsupported system type:", os)
    }
  }

  # 生成函数get_latest_release_selenium获取最新版本的selenium
  get_latest_release_selenium <- function(selenium_base_url, selenium_backup_url) {
    versions_page <- tryCatch({
      rvest::read_html(selenium_base_url)
    }, error = function(e) {
      cat("Error: Failed to access the primary URL. Trying the backup URL...\n")
      rvest::read_html(selenium_backup_url)
    })

    latest_version <- versions_page |>
      rvest::html_nodes(xpath = "//key[contains(text(), 'selenium-server-standalone')]") |>
      rvest::html_text()
    latest_version_jar <- grep(".jar$", latest_version, value = T) |> tail(1)
    selenium_name <- gsub("^[0-9.]+/", "", latest_version_jar)
    selenium_file <- file.path(download_path, selenium_name)
    # 下载最新版本的selenium-server-standalone（如果selenium_file不存在）
    selenium_url <- paste0(selenium_base_url, latest_version_jar)
    backup_selenium_url <- paste0(selenium_backup_url, latest_version_jar)

    if (httr::http_status(httr::GET(selenium_url))$category == "Success") {
      return(selenium_url)
    } else if (httr::http_status(httr::GET(backup_selenium_url))$category == "Success") {
      return(backup_selenium_url)
    } else {
      stop("Both URLs are not available.")
    }
  }

  # 生成函数,下载文件的辅助函数
  download_with_error_handling <- function(url, file, ...) {
    tryCatch(
      {
        download.file(url, file, ...)
      },
      error = function(cond) {
        cat(paste0("An error occurred while downloading \n",
                   file, "\n"))
        message(cond)
      }
    )
  }

  # 下生成函数,载浏览器驱动并提取
  download_and_extract_driver <- function(browser, download_path, version_pattern, base_url, backup_url = NULL) {

    # 检查浏览器驱动文件是否存在
    browser_file <- file.path(download_path, version_pattern)

    # 如果浏览器驱动文件不存在，则执行以下操作
    if (!file.exists(browser_file)) {

      if (browser == "chrome") {
        latest_release_url <- get_latest_release_chrome(base_url, backup_url)
      } else if (browser == "edge") {
        latest_release_url <- get_latest_release_edge(base_url)
      } else {
        stop("Error: Unsupported browser. Please specify either 'chrome' or 'edge'.")
      }

      if (is.null(latest_release_url)) {
        stop(paste("Error: Failed to fetch the latest", browser, "driver release."))
      }

      # 截取 URL 中的文件名
      file_name <- basename(latest_release_url)

      # 拼接完整的下载文件路径
      download_file <- file.path(download_path, file_name)#paste0(download_path, "/", file_name)

      # 下载文件
      download_with_error_handling(latest_release_url, download_file, method = "curl")

      # 解压缩文件
      unzip(download_file, exdir = download_path)

      # 删除下载的压缩文件
      file.remove(download_file)
    }
  }


  # 生成函数download_selenium,下载selenium
  selenium_base_url <- "https://selenium-release.storage.googleapis.com/"
  selenium_backup_url <- "https://mirrors.huaweicloud.com/selenium/" # 请替换为您的备份网址
  download_selenium <- function(download_path, selenium_base_url, selenium_backup_url) {

    # 检查浏览器驱动文件是否存在
    existing_files <- list.files(download_path, pattern = ".jar$", full.names = TRUE)

    # 如果浏览器驱动文件不存在，则执行以下操作
    if (length(existing_files) == 0) {

      latest_release_url <- get_latest_release_selenium(selenium_base_url,selenium_backup_url) #获取最新版本selenium

      # 截取 URL 中的文件名
      file_name <- basename(latest_release_url)

      # 拼接完整的下载文件路径
      download_file <- file.path(download_path, file_name)#paste0(download_path, "/", file_name)

      # 下载文件
      download_with_error_handling(latest_release_url, download_file, method = "curl")
    }
  }

  # 生成selenium启动函数，启动selenium并生成开机启动的.bat文件
  start_selenium_server <- function(browser, download_path) {
    # Step 3: 启动Selenium服务器（如果尚未运行）
    task_list <- system2("wmic", args = c("process", "where", "name='java.exe'", "get", "ProcessId,CommandLine"), stdout = TRUE)
    # 使用 stri_encode 转换编码
    task_list <- stringi::stri_encode(task_list, from = "", to = "UTF-8")
    task_list_lines <- unlist(strsplit(task_list, split = "\r\n"))
    task_list_lines <- task_list_lines[grep("selenium-server-standalone", task_list_lines)]

    if (length(task_list_lines) > 0) {
      # 如果已有一个正在运行的 Selenium 服务器进程，等待它结束
      for (line in task_list_lines) {
        pid <- as.integer(gsub("^.*?([0-9]+).*$", "\\1", line))
        system2("taskkill", args = c("/F", "/PID", pid), stdout = FALSE, stderr = FALSE)
        cat(sprintf("Old selenium server process with PID %d terminated.\n", pid))
      }
      Sys.sleep(5) # 等待一段时间以确保进程已经结束
    }

    # 启动一个新的 Selenium 服务器进程
    startup_path <- file.path(Sys.getenv("APPDATA"), "Microsoft", "Windows", "Start Menu", "Programs", "Startup")
    startup_path <- gsub("\\\\", "/", startup_path)

    if (browser == "chrome") {
      browser_file <- file.path(download_path, "chromedriver.exe")# Chrome 驱动程序文件路径
      bat_file <- file.path(startup_path, "chrome_driver.bat")
    } else if (browser == "edge") {
      browser_file <- file.path(download_path, "msedgedriver.exe")# Edge 驱动程序文件路径
      bat_file <- file.path(startup_path, "edge_driver.bat")
    } else {
      stop("Invalid browser specified.")
    }

    selenium_file <- list.files(download_path, pattern = ".jar$", full.names = TRUE) # Selenium 服务器文件路径
    command <- sprintf("java -Dwebdriver.%s.driver=\"%s\" -jar \"%s\"", browser, browser_file, selenium_file)
    status <- system(command, wait = FALSE)
    if (status != 0) {
      cat("Error: Failed to start Selenium server.")
    } else {
      cat("New selenium server process created.")
    }
    # Step 4: 实现开机启动（如果.bat文件尚未创建）
    if (!file.exists(bat_file)) {

      bat_content <- paste(
        "@echo off",
        "cd /d %~dp0",
        "if \"%1\" == \"h\" goto begin",
        "mshta vbscript:createobject(\"wscript.shell\").run(\"%~nx0 h\",0)(window.close)&&exit",
        ":begin",
        command,
        sep = "\n")

      writeLines(bat_content, con = bat_file)
    }
  }

  if (browser == "chrome") {
    base_url <- "https://chromedriver.storage.googleapis.com"
    backup_url <- "https://mirrors.huaweicloud.com/chromedriver/"# 替换成实际的备份网址
    version_pattern <- "chromedriver.exe"
    browser = "chrome"
    browser_name = "Chrome" #仅用于check_browser_installed
    # 检查浏览器安装情况
    check_browsers_installed(browser_name)
    download_and_extract_driver(browser, download_path, version_pattern, base_url, backup_url)
    download_selenium(download_path, selenium_base_url, selenium_backup_url)
    start_selenium_server(browser, download_path)
  } else if (browser == "edge") {
    base_url <- "https://msedgedriver.azureedge.net/"
    version_pattern <- "msedgedriver.exe"
    browser = "edge"
    browser_name = "Microsoft Edge" #仅用于check_browser_installed
    # 检查浏览器安装情况
    check_browsers_installed(browser_name)
    download_and_extract_driver(browser, download_path, version_pattern, base_url)
    download_selenium(download_path, selenium_base_url, selenium_backup_url)
    start_selenium_server(browser, download_path)
  }
}
