# WARNING - Generated by {fusen} from dev/csv_download.Rmd: do not edit by hand

#' stop chrome or edge broser dirver and selenium server
#' 
#' @description
#'
#' `disconnect_from_browser()` is deprecated. We will soon be totally
#' 
#'
#' @return NULL
#' 
#' @export
#' @examples
#' disconnect_from_browser()

disconnect_from_browser <- function() {
  wdauto::reset_cs()
}
