# WARNING - Generated by {fusen} from /dev/csv_download.Rmd: do not edit by hand

#' stop chrome or edge broser dirver and selenium server
#' 
#' @description
#'
#' `disconnect_from_browser()` is deprecated. We will soon be totally
#' 
#'
#' @return NULL
#' 
#' @export

#' @examples
#' disconnect_from_browser()
disconnect_from_browser <- function() {

  # Step 1: 关闭Selenium服务器
  task_list <- system2("wmic", args = c("process", "where", "name='java.exe'", "get", "ProcessId,CommandLine"), stdout = TRUE)
  # 使用 stri_encode 转换编码
  task_list <- stringi::stri_encode(task_list, from = "", to = "UTF-8")
  task_list_lines <- unlist(strsplit(task_list, split = "\r\n"))
  task_list_lines <- task_list_lines[grep("selenium-server-standalone", task_list_lines)]

  if (length(task_list_lines) > 0) {
    for (line in task_list_lines) {
      pid <- as.integer(gsub("^.*?([0-9]+).*$", "\\1", line))
      system2("taskkill", args = c("/F", "/PID", pid), stdout = FALSE, stderr = FALSE)
      cat(sprintf("Selenium server process with PID %d terminated.\n", pid))
    }
  } else {
    cat("No Selenium server process found.\n")
  }

  # Step 2: 关闭所有正在运行的chromedriver.exe进程
  chromedriver_list <- system2("wmic", args = c("process", "where", "name='chromedriver.exe'", "get", "ProcessId,CommandLine"), stdout = TRUE)
  # 使用 stri_encode 转换编码
  chromedriver_list <- stringi::stri_encode(chromedriver_list, from = "", to = "UTF-8")
  chromedriver_list_lines <- unlist(strsplit(chromedriver_list, split = "\r\n"))
  chromedriver_list_lines <- chromedriver_list_lines[grep("chromedriver.exe", chromedriver_list_lines)]

  if (length(chromedriver_list_lines) > 0) {
    for (line in chromedriver_list_lines) {
      pid <- as.integer(gsub("^.*?([0-9]+).*$", "\\1", line))
      system2("taskkill", args = c("/F", "/PID", pid), stdout = FALSE, stderr = FALSE)
      cat(sprintf("Chromedriver process with PID %d terminated.\n", pid))
    }
  } else {
    cat("No Chromedriver process found.\n")
  }

  # 关闭所有正在运行的 msedgedriver.exe 进程
  msedgedriver_list <- system2("wmic", args = c("process", "where", "name='msedgedriver.exe'", "get", "ProcessId,CommandLine"), stdout = TRUE)
  # 使用 stri_encode 转换编码
  msedgedriver_list <- stringi::stri_encode(msedgedriver_list, from = "", to = "UTF-8")
  msedgedriver_list_lines <- unlist(strsplit(msedgedriver_list, split = "\r\n"))
  msedgedriver_list_lines <- msedgedriver_list_lines[grep("msedgedriver.exe", msedgedriver_list_lines)]

  if (length(msedgedriver_list_lines) > 0) {
    for (line in msedgedriver_list_lines) {
      pid <- as.integer(gsub("^.*?([0-9]+).*$", "\\1", line))
      system2("taskkill", args = c("/F", "/PID", pid), stdout = FALSE, stderr = FALSE)
      cat(sprintf("Microsoft Edge driver process with PID %d terminated.\n", pid))
    }
  } else {
    cat("No Msedgedriver process found.\n")
  }

  # Step 2: 取消开机启动
  startup_path <- file.path(Sys.getenv("APPDATA"), "Microsoft", "Windows", "Start Menu", "Programs", "Startup")
  startup_path <- gsub("\\\\", "/", startup_path)
  #bat_file <- file.path(startup_path, "chrome_driver.bat")
  bat_file <- list.files(startup_path, ".bat$", full.names = T)

  if (length(bat_file) > 0) {
    file.remove(bat_file)
    cat("Startup .bat file removed.\n")
  } else {
    cat("No startup .bat file found.\n")
  }
}
