# WARNING - Generated by {fusen} from dev/csv_download.Rmd: do not edit by hand

#' Reset selenium webdriver service
#' 
#' @description
#'
#' `disconnect_from_browser()` is used to reset selenium webdriver service.
#'
#' @return NULL
#' 
#' @importFrom wdauto "reset_cs"
#' @export
#' @examples
#' disconnect_from_browser()

disconnect_from_browser <- function() {
  wdauto::reset_cs()
}
