# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' download_free_brain
#' 
#' @param location Numeric value in string format
#' @param data_date The dates of data download
#' @param ... other parameters
#' 
#' @return CSV files in the download path of your Google Chrome web browser.
#' @export

#' @examples
#' user_name = "隆鑫场测定一区"
#' stations = purrr::map_chr(seq(101L,103L,1L), c)
#' download_date = seq(as.Date("2023-02-01"),as.Date("2023-02-03"),1)
#' download_free_brain(location = stations, 
#'                     data_date = download_date, 
#'                     url = Sys.getenv("web_url"), 
#'                     username = user_name, 
#'                     password = Sys.getenv("user_password"))
download_free_brain <- function(location, data_date, ...){ 
  purrr::map(data_date, ~download_free_hands(location, ...), ...)
}
