# WARNING - Generated by {fusen} from /dev/flat_teaching.Rmd: do not edit by hand

#' Add one to any value
#' 
#' @param location A numeric value
#' @param data_date The date of data download
#' @param url The url of pig performance test station website
#' @param username The username of pig performance test station website
#' @param password The password of pig performance test station website
#' @param ... other parameters
#'
#' @return csv datas
#' @export

#' @examples
#' web_ppt1 <- "https://yxlxppt01.vpu-online.cn/login/LoginPage.web"
#' username1 <- "隆鑫场测定一区"
#' password1 <- "yangxianglongxin1234"
#' station_create5 <- purrr::map_chr(seq(101L,102L,1L), c)
#' download_by_hand(location = station_create5, 
#'                  data_date = "2023-02-11", 
#'                  url = web_ppt1, 
#'                  username = username1, 
#'                  password = password1)
#' 
download_by_hand <- function(location, data_date, url, username, password, ...){
  remDr <- RSelenium::remoteDriver(remoteServerAddr = "127.0.0.1"
                        , port = 4444
                        , browserName = "chrome")#连接Server

  remDr$open() #打开浏览器
  remDr$navigate(url) #打开网址

  login_user <- '//*[@id="frmLogin"]/div[2]/input'
  login_passwd <- '//*[@id="frmLogin"]/div[3]/input'

  login_user_ele<-remDr$findElement("xpath",login_user)
  login_passwd_ele<-remDr$findElement("xpath",login_passwd)
  user<-list(username)
  pass<-list(password)
  login_user_ele$sendKeysToElement(user)
  login_passwd_ele$sendKeysToElement(pass)

  login <- '//*[@id="login_button"]'
  login_ele<-remDr$findElement("xpath",login)
  remDr$mouseMoveToLocation(webElement = login_ele)
  remDr$click()

  #Sys.sleep(5)
  Sys.sleep(sample(10,1))

  iter_download <- function(station, data_date, ...){
    #选择nedap网站《报告》
    choose_item <- '/html/body/div[1]/div[1]/ul/li[4]/a'
    choose_ele<-remDr$findElement("xpath",choose_item)
    remDr$mouseMoveToLocation(webElement = choose_ele)
    remDr$click()

    #选择<报告>中的<下载csv数据>
    download_item <- '//*[@id="reports_page"]/div[2]/div/div[3]/ol/li[4]/a'
    #download_item <- '//*[@id="reports_page"]/div[2]/div/div[3]/ol/li[1]/a'
    download_ele<-remDr$findElement("xpath",download_item)
    remDr$mouseMoveToLocation(webElement = download_ele)
    remDr$click()

    #choose_locations
    location_start <- '//*[@id="criteria"]/report-selection-range/div/div/div/div[1]/input'
    location_end <- '//*[@id="criteria"]/report-selection-range/div/div/div/div[2]/input'
    location_ele_start<-remDr$findElement("xpath",location_start)
    location_ele_end<-remDr$findElement("xpath",location_end)

    location_ele_start$clearElement() #清空输入框内容
    location_ele_end$clearElement() #清空输入框内容

    location_start_num <- list(station, key = "enter")
    location_ele_start$sendKeysToElement(location_start_num)
    location_ele_end$clickElement()#单击鼠标
    #选择下载日期
    date_start <- '//*[@id="datetimepicker0"]/input'
    date_end <- '//*[@id="datetimepicker1"]/input'
    date_ele_start<-remDr$findElement("xpath",date_start)
    date_ele_end<-remDr$findElement("xpath",date_end)

    date_ele_start$clearElement() #清空输入框内容

    date_need_to_download <- stringr::str_replace_all(as.character(data_date),"-",".")

    date_start_num <- list(date_need_to_download, key = "enter")
    date_end_num <- list(date_need_to_download, key = "enter")
    date_ele_start$sendKeysToElement(date_start_num)
    date_ele_end$clearElement()
    date_ele_end$sendKeysToElement(date_end_num)

    #download csv数据
    download_button <- '//*[@id="reports_download_csv_data"]/div[4]/button'
    download_button_ele<-remDr$findElement("xpath",download_button)
    remDr$mouseMoveToLocation(webElement = download_button_ele)
    remDr$click()

    remDr$refresh() #刷新网页
  }
  purrr::walk2(location, data_date, iter_download, ...)
  remDr$quit()
}
