# WARNING - Generated by {fusen} from dev/csv_download.Rmd: do not edit by hand

#' Direct web scraping CSVs
#' 
#' @description
#' 
#' `get_csv()` allows you to directly download CSV files from the web. You can download CSV data for a specific location range or date range. 
#'
#' @param url A character string specifying the URL to log into.
#' @param username A character string specifying the username for login.
#' @param password A character string specifying the password for login.
#' @param location_min A character string specifying the minimum location.
#' @param location_max A character string specifying the maximum location.
#' @param date_min A Date object specifying the earliest date.
#' @param date_max A Date object specifying the latest date.
#' @param download_path A character string specifying the path where the downloaded CSV file should be saved.
#' @param show_message A logical value. If TRUE, a message will be displayed after the download. Default is FALSE.
#'
#' @return CSVs in the path of download_path.
#' 
#' @export
#' @examples
#' # Download CSV data for a specific location range or date range.
#' get_csv(url = Sys.getenv("url"),
#'         username = Sys.getenv("username"),
#'         password = Sys.getenv("password"),
#'         location_min = "406",
#'         location_max = "407",
#'         date_min = "2024-02-18",
#'         date_max = "2024-02-19",
#'         download_path = "C:/Users/Dell/Downloads/download_rename", 
#'         show_message = TRUE)

get_csv <- function(url, username, password, location_min, location_max, date_min, date_max, download_path, show_message = FALSE) {
  login_nedap(url, username, password) |>
    download_csv(location_min, location_max, date_min, date_max, download_path, show_message)
}

is_error_response <- function(resp) {
  httr2::resp_status(resp) >= 400
}

error_message_body <- function(resp) {
  paste("Error occurred with status code:", httr2::resp_status(resp))
}

login_nedap <- function(url, username, password) {
  # check if input parameters are missing
  if (missing(url) | missing(username) | missing(password)) {
    stop("Missing required input parameter(s).")
  }

  # check input parameters
  stopifnot(is.character(url), length(url) == 1)
  stopifnot(is.character(username), length(username) == 1)
  stopifnot(is.character(password), length(password) == 1)

  # create login request
  login_request <- httr2::request(paste0(url, "/login/LoginPage.web")) |>
    httr2::req_method("post") |>
    httr2::req_body_form(select_username = username, input_password = password) |>
    httr2::req_cookie_preserve(path = tempfile())

  # perform the request and get response
  login_response <- httr2::req_perform(login_request)

  # check if login is successful
  if (httr2::resp_status(login_response) != 200) {
    stop("Failed to login, please check your username or password.")
  }

  # get the login respond
  login_respond <- login_request |>
    httr2::req_retry(max_tries = 3, is_transient = \(resp) httr2::resp_status(resp) %in% c(429, 500, 503), backoff = ~10) |>
    httr2::req_error(is_error = is_error_response, body = error_message_body) |>
    httr2::req_url(paste0(url, "/pigperformancetesting/reports/DownloadCsvDataReport.web"))

  return(login_respond)
}

download_csv <- function(login_respond, location_min, location_max, date_min, date_max, download_path, show_message) {
  # check if input parameters are missing
  if (missing(login_respond) | missing(location_min) | missing(location_max) | missing(date_min) | missing(date_max) | missing(download_path)) {
    stop("Missing required input parameter(s).")
  }

  # check input parameters
  stopifnot(is.character(location_min), length(location_min) == 1)
  stopifnot(is.character(location_max), length(location_max) == 1)
  stopifnot(is.character(date_min), length(date_min) == 1)
  stopifnot(is.character(date_max), length(date_max) == 1)
  stopifnot(is.character(download_path), length(download_path) == 1)

  # create params
  params <- list(location_min = location_min, location_max = location_max, date_min = as.character(paste0(date_min, "T00:00:00Z")), date_max = as.character(paste0(date_max, "T00:00:00Z")))

  # perform the request and get response
  login_respond <- login_respond |>
    httr2::req_url_query(generate = "1", !!!params) |>
    httr2::req_perform()

  # check if the request is successful
  if (httr2::resp_status(login_respond) != 200) {
    stop("Failed to download csv, please check your parameters.")
  }

  # get the content and write to file
  content <- httr2::resp_body_string(login_respond)
  # check if location_min and location_max, date_min and date_max are the same
  location <- if(location_min == location_max) location_min else paste(location_min, location_max, sep="_")
  date <- if(date_min == date_max) date_min else paste(date_min, date_max, sep="_")
  filename <- paste0(location, "_location_", date, "_date_", Sys.Date(), "_download.csv")
  writeLines(content, file.path(download_path, filename))
  if (show_message) {
    cat(crayon::blue("\u25CF"), "Locations:", location, "and Dates:", date, "downloaded\n")
  }
}
