# WARNING - Generated by {fusen} from dev/csv_download.Rmd: do not edit by hand

#' Direct web scraping CSVs
#' 
#' @description
#' 
#' `get_csv_auto` allows you to directly download CSV files from the web. You can download CSV data for a specific location or date.
#'
#' @param url A character string specifying the URL to log into.
#' @param username A character string specifying the username for login.
#' @param password A character string specifying the password for login.
#' @param location A character string specifying the location.
#' @param date A Date object specifying the date.
#' @param download_path A character string specifying the path where the downloaded CSV file should be saved.
#' @param show_message A logical value. If TRUE, a message will be displayed after the download. Default is FALSE.
#'
#' @return CSVs in the path of download_path.
#' 
#' @importFrom cli "pb_spin" "pb_current" "pb_total"
#' @export
#' @examples
#' # Download CSV data for a specific location or date
#' get_csv_auto(url = Sys.getenv("url"),
#'              username = Sys.getenv("username"),
#'              password = Sys.getenv("password"),
#'              location = c("607","608"),
#'              date = c("2024-02-18", "2024-02-19"),
#'              download_path = "C:/Users/Dell/Downloads/download_rename")

get_csv_auto <- function(url, username, password, location, date, download_path, show_message = FALSE){
  login_request <- login_nedap(url, username, password)
  download_oneday_eachstation <- function(location, date) {
    download_csv(login_respond = login_request, location_min = location, location_max = location, date_min = date, date_max = date, download_path, show_message)
  }
  all_station_perday <- function(date) {
    # check if input parameter is missing
    if (missing(date)) {
      stop("Missing required input parameter: date.")
    }

    # check input parameter
    stopifnot(length(date) == 1)

    # Convert the integer date to a Date object and format it
    date <- format(as.Date(date), "%Y-%m-%d")

    # create a data frame with all combinations of location and date
    all_comb_station <- tidyr::expand_grid(location = location, date = date)

    cat(crayon::yellow("\u25CF"), "Downloading CSVs for date:", date, "\n")

    # download the csv file for each combination of location and date
    purrr::pwalk(all_comb_station, ~download_oneday_eachstation(location = ..1, date = ..2), .progress = F)

    #cat(crayon::yellow("\u25CF"), "Downloading CSVs for date:", date, "\n")
  }
  purrr::walk(date, all_station_perday, .progress = list(
    type = "iterator",
    format = "{cli::pb_spin} Downloading {cli::pb_current}/{cli::pb_total} dates",
    clear = TRUE))
  cat(crayon::green("\u25CF"), "All stations and dates nedap ppt CSVs had been downloaded.\n")

}
